
log4j.rootLogger=INFO, stdout, dailylog

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - %m%n
log4j.appender.stdout.Threshold=info

#
# Daily based logging configuration
#
log4j.appender.dailylog = org.apache.log4j.DailyRollingFileAppender
log4j.appender.dailylog.File = C:\\logs\\wa-depo
log4j.appender.dailylog.Append = true
log4j.appender.dailylog.DatePattern = '.'yyyy_MM_dd'.log'
log4j.appender.dailylog.layout = org.apache.log4j.PatternLayout
log4j.appender.dailylog.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %c{1} [%p] %m%n
log4j.appender.dailylog.Threshold=INFO

log4j.logger.org.hibernate=info
log4j.logger.org.hibernate.SQL=info
log4j.logger.org.hibernate.type.descriptor.sql=info
log4j.logger.org.hibernate.orm.deprecation=error
log4j.logger.com.zaxxer.hikari.HikariConfig.logConfiguration=info
log4j.logger.com.zaxxer.hikari.pool.HikariPool.logPoolState=info

